title: abapGit documentation
keep_files: [explore.html, repos.json]
highlighter: rouge
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
